### ISSUE TITLE
Not an issue per se

### ISSUE THREAD

**Issue by vishalg0wda** [quodlibetor/jsonlogprint#1]
https://github.com/quodlibetor/jsonlogprint/blob/d029fc6802d7102f7706952b6238c064d071fe4d/jsonlogprint/src/main.rs#L163

Just wanted to understand if this referencing necessitates the usage of `std::borrow:Cow`.

**Comment by quodlibetor** [comment]
Do you mean this one in deser? https://github.com/quodlibetor/jsonlogprint/blob/d029fc6802d7102f7706952b6238c064d071fe4d/jsonlogprint/src/deser.rs#L13-L15

I don't recall the exact details of why I added it, but it doesn't seem necessary any more: #2

**Comment by quodlibetor** [comment]
oh lol that's right, I couldn't get deserialization to work without it:

```
---- tests::test_transform_lines_with_newlines_in_message stdout ----
2024-11-27T15:09:20.169529Z DEBUG jsonlogprint: Failed to deserialize JSON line line={"timestamp":1627494000,"level":"info","msg":"Test message with\nnewline"} error=data did not match any variant of untagged enum JsonValue at line 1 column 74
thread 'tests::test_transform_lines_with_newlines_in_message' panicked at jsonlogprint/src/main.rs:400:9:
assertion `left == right` failed
  left: "2021-07-28T17:40:00Z info\nmsg=\"Test message with\nnewline\"\n"
 right: "{\"timestamp\":1627494000,\"level\":\"info\",\"msg\":\"Test message with\\nnewline\"}\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by quodlibetor** [comment]
Oh it's because a string with json-escaped characters (e.g. `"error:\nexplanation"`, `"\t"`) needs an allocation to convert the escape into a byte.

**Comment by vishalg0wda** [comment]
Yep. I was wrestling with `Cow` for a while - reading your code [sent me on a journey](https://github.com/vishalg0wda/jedison/blob/master/examples/cow.rs). A very enlightening one I must say. :)
